version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  site:
    build: .
    networks:
      - proxy-tier
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: "testing.wise.vote/voting-page"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 8080
      CADDY_TIMEOUTS: "read 5m, write 2m"
